[2023-03-25 13:33:23,434] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.print_projects scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2023-03-25 13:33:23,457] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.print_projects scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2023-03-25 13:33:23,465] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:33:23,467] {taskinstance.py:1357} INFO - Starting attempt 6 of 6
[2023-03-25 13:33:23,475] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:33:23,495] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): print_projects> on 2023-02-11 00:00:00+00:00
[2023-03-25 13:33:23,511] {standard_task_runner.py:52} INFO - Started process 950 to run task
[2023-03-25 13:33:23,516] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'print_projects', 'scheduled__2023-02-11T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpmemrb73k', '--error-file', '/tmp/tmp8qquw8oi']
[2023-03-25 13:33:23,525] {standard_task_runner.py:80} INFO - Job 74: Subtask print_projects
[2023-03-25 13:33:23,617] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.print_projects scheduled__2023-02-11T00:00:00+00:00 [running]> on host 6614738016e4
[2023-03-25 13:33:23,757] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=print_projects
AIRFLOW_CTX_EXECUTION_DATE=2023-02-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-11T00:00:00+00:00
[2023-03-25 13:33:23,780] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-25 13:33:23,793] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl http://localhost:6800/listprojects.json']
[2023-03-25 13:33:23,848] {subprocess.py:85} INFO - Output:
[2023-03-25 13:33:23,990] {subprocess.py:92} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-03-25 13:33:23,992] {subprocess.py:92} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-03-25 13:33:24,000] {subprocess.py:92} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2023-03-25 13:33:24,002] {subprocess.py:92} INFO - curl: (7) Failed to connect to localhost port 6800: Connection refused
[2023-03-25 13:33:24,004] {subprocess.py:96} INFO - Command exited with return code 7
[2023-03-25 13:33:24,038] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2023-03-25 13:33:24,052] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=rightmove_extraction_dag, task_id=print_projects, execution_date=20230211T000000, start_date=20230325T133323, end_date=20230325T133324
[2023-03-25 13:33:24,078] {standard_task_runner.py:92} ERROR - Failed to execute job 74 for task print_projects (Bash command failed. The command returned a non-zero exit code 7.; 950)
[2023-03-25 13:33:24,111] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-25 13:33:24,163] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
