[2023-03-25 13:33:30,814] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.print_projects scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-03-25 13:33:30,831] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: rightmove_extraction_dag.print_projects scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-03-25 13:33:30,835] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:33:30,840] {taskinstance.py:1357} INFO - Starting attempt 6 of 6
[2023-03-25 13:33:30,841] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-25 13:33:30,861] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): print_projects> on 2023-02-12 00:00:00+00:00
[2023-03-25 13:33:30,877] {standard_task_runner.py:52} INFO - Started process 970 to run task
[2023-03-25 13:33:30,889] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rightmove_extraction_dag', 'print_projects', 'scheduled__2023-02-12T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/rightmove_extraction_dag.py', '--cfg-path', '/tmp/tmpgrym32k2', '--error-file', '/tmp/tmpy_rbwxl2']
[2023-03-25 13:33:30,896] {standard_task_runner.py:80} INFO - Job 78: Subtask print_projects
[2023-03-25 13:33:31,050] {task_command.py:369} INFO - Running <TaskInstance: rightmove_extraction_dag.print_projects scheduled__2023-02-12T00:00:00+00:00 [running]> on host 6614738016e4
[2023-03-25 13:33:31,682] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alex
AIRFLOW_CTX_DAG_ID=rightmove_extraction_dag
AIRFLOW_CTX_TASK_ID=print_projects
AIRFLOW_CTX_EXECUTION_DATE=2023-02-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-12T00:00:00+00:00
[2023-03-25 13:33:31,705] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-25 13:33:31,726] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl http://localhost:6800/listprojects.json']
[2023-03-25 13:33:31,806] {subprocess.py:85} INFO - Output:
[2023-03-25 13:33:31,906] {subprocess.py:92} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-03-25 13:33:31,908] {subprocess.py:92} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-03-25 13:33:31,916] {subprocess.py:92} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2023-03-25 13:33:31,919] {subprocess.py:92} INFO - curl: (7) Failed to connect to localhost port 6800: Connection refused
[2023-03-25 13:33:31,925] {subprocess.py:96} INFO - Command exited with return code 7
[2023-03-25 13:33:31,962] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2023-03-25 13:33:31,967] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=rightmove_extraction_dag, task_id=print_projects, execution_date=20230212T000000, start_date=20230325T133330, end_date=20230325T133331
[2023-03-25 13:33:31,993] {standard_task_runner.py:92} ERROR - Failed to execute job 78 for task print_projects (Bash command failed. The command returned a non-zero exit code 7.; 970)
[2023-03-25 13:33:32,045] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-25 13:33:32,127] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
